# Generated by Django 5.0.4 on 2024-05-12 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('histID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetHistorial',
            fields=[
                ('detHistID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('Recipe', models.CharField(max_length=255)),
                ('Instructions', models.CharField(max_length=255)),
                ('histID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartcook.historial')),
            ],
        ),
        migrations.CreateModel(
            name='TempImg',
            fields=[
                ('imgID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
