# Generated by Django 5.0.4 on 2024-05-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimg',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to='png/'),
        ),
    ]
