# Generated by Django 5.0.4 on 2024-05-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0002_alter_tempimg_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempimg',
            old_name='data',
            new_name='image',
        ),
    ]
