# Generated by Django 5.0.4 on 2024-05-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0003_rename_data_tempimg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempimg',
            name='url',
        ),
    ]
