# Generated by Django 5.0.4 on 2024-05-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0004_remove_tempimg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tempImg/'),
        ),
    ]
