# Generated by Django 5.0.4 on 2024-05-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0006_alter_tempimg_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimg',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='tempImg/'),
        ),
    ]
