# Generated by Django 5.0.4 on 2024-06-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0007_alter_tempimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tempImg/'),
        ),
    ]
