# Generated by Django 5.0.4 on 2024-06-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0008_alter_tempimg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='userID',
        ),
        migrations.DeleteModel(
            name='TempImg',
        ),
    ]
