# Generated by Django 5.0.6 on 2024-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcook', '0010_historial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethistorial',
            name='Ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dethistorial',
            name='Instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dethistorial',
            name='Recipe',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
