# Generated by Django 5.0.4 on 2024-05-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_user_superuser_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
