# Generated by Django 5.0.4 on 2024-06-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_user_history_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
    ]
