
name: Build, and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build
        
      - name: Generate Tag Name
        id: tag
        run: echo "tag_name=release-$(date +%Y-%m-%d)-${{ github.run_number }}" >> $GITHUB_OUTPUT
