
name: Build, and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build
        
      - name: Generate Tag Name
        id: tag
        run: echo "tag_name=release-$(date +%Y-%m-%d)-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          release_name: Release ${{ steps.tag.outputs.tag_name }}
          body: |
            Automated release triggered by commit ${{ github.sha }}.
            The Docker images were successfully built.
          draft: false
          prerelease: false

      - name: Create Source Code Archive
        run: tar -czf source-code.tar.gz --exclude='.git' --exclude='.github' .

      - name: Upload Source Code to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source-code.tar.gz
          asset_name: source-code-${{ steps.tag.outputs.tag_name }}.tar.gz
          asset_content_type: application/gzip
